simlex/Controllers/ArticlesController.cs
using simlex.Models;
using simlex.ViewModels;
using SX.WebCore.SxRepositories;
using simlex.Infrastructure.Repositories;
using simlex.Controllers.Abstract;
using System.Web.Mvc;
using System.Threading.Tasks;
using SX.WebCore.MvcControllers;

namespace simlex.Controllers
{
    public sealed class ArticlesController : MaterialsController<Article, VMArticle>
    {
        public ArticlesController() : base(ModelCoreTypeProvider[nameof(Article)]) { }

        private static readonly RepoArticle _repo = new RepoArticle();
        public override SxRepoMaterial<Article, VMArticle> Repo
        {
            get
            {
                return _repo;
            }
        }

        [HttpGet]
        public async Task<ActionResult> Details(int year, string month, string day, string titleUrl)
        {
            var viewModel = await Repo.GetByTitleUrlAsync(year, month, day, titleUrl);
            if (viewModel == null) return new HttpNotFoundResult();
            viewModel.RelatedMaterials = await Repo.GetRelatedAsync<VMMaterial>(new SX.WebCore.SxFilter(1, 5) {
                MaterialId=viewModel.Id,
                ModelCoreType=viewModel.ModelCoreType
            });
            viewModel.Comments = await SxCommentsController.Repo.ReadAsync(new SX.WebCore.SxFilter(1, 10)
            {
                MaterialId=viewModel.Id,
                ModelCoreType=viewModel.ModelCoreType
            });

            return View(model: viewModel);
        }

#if !DEBUG
        [OutputCache(Duration = 3600)]
#endif
        public PartialViewResult Statistic()
        {
            var viewModel = new VMMaterialsStatisticBlock()
            {
                Materials = Repo.Read(new SX.WebCore.SxFilter(1, 10)),
                CommentedMaterials = Repo.LastCommented<VMMaterial>(new SX.WebCore.SxFilter(1, 10) { ModelCoreType=1 }),
                Tags = SxMaterialTagsController.Repo.GetCloud(new SX.WebCore.SxFilter(1, 10))
            };

            return PartialView("_Statistic", viewModel);
        }
    }
}

simlex/Controllers/ProjectsController.cs
using simlex.Controllers.Abstract;
using simlex.Infrastructure.Repositories;
using simlex.Models;
using simlex.ViewModels;
using SX.WebCore.MvcApplication;
using SX.WebCore.MvcControllers;
using SX.WebCore.SxRepositories;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace simlex.Controllers
{
    public sealed class ProjectsController : MaterialsController<Project, VMProject>
    {
        private static readonly RepoProject _repo = new RepoProject();
        public override SxRepoMaterial<Project, VMProject> Repo
        {
            get
            {
                return _repo;
            }
        }
        public ProjectsController() : base(SxMvcApplication.ModelCoreTypeProvider[nameof(Project)]) { }

#if !DEBUG
        [OutputCache(Duration = 3600, VaryByParam = "titleUrl")]
#endif
        [HttpGet]
        public async Task<ActionResult> Details(string titleUrl)
        {
            var viewModel = await Repo.GetByTitleUrlAsync(null, null, null, titleUrl);
            if (viewModel == null) return new HttpNotFoundResult();

            viewModel.Comments = await SxCommentsController.Repo.ReadAsync(new SX.WebCore.SxFilter(1, 10)
            {
                MaterialId = viewModel.Id,
                ModelCoreType = viewModel.ModelCoreType
            });

            return View(model: viewModel);
        }
    }
}

simlex/Controllers/SiteNetsController.cs
using SX.WebCore.MvcControllers;
using System.Web.Mvc;
using System.Linq;
using simlex.ViewModels;
using SX.WebCore.DbModels;
using SX.WebCore.ViewModels;
using System.Net;
using System;

namespace simlex.Controllers
{
    public sealed class SiteNetsController : SxSiteNetsController
    {
        [AllowAnonymous, ChildActionOnly]
        public PartialViewResult Accordion()
        {
            var viewModel = SX.WebCore.MvcApplication.SxMvcApplication.CacheProvider.Get<VMNetAccordion>("CACHE_NETS_ACCORDION");
            if (viewModel != null) return PartialView("_Accordion", viewModel);

            viewModel = new VMNetAccordion();
            var nets = SX.WebCore.MvcApplication.SxMvcApplication.SiteNetsProvider.All;
            viewModel.Nets = nets.Select(Mapper.Map<SxSiteNet, SxVMSiteNet>).ToArray();
            if (viewModel.Nets.Any() && !Request.IsLocal)
            {
                SxVMSiteNet item;
                for (int i = 0; i < viewModel.Nets.Length; i++)
                {
                    item = viewModel.Nets[i];
                    switch (item.Net.Code)
                    {
                        case "vk":
                            var list = getVkUsers();
                            viewModel.Items.Add(item.Net.Code, list);
                            break;
                    }
                }
            }

            SX.WebCore.MvcApplication.SxMvcApplication.CacheProvider.Set("CACHE_NETS_ACCORDION", viewModel, 60);
            return PartialView("_Accordion", viewModel);
        }

        private static SX.VkApi.Models.User[] getVkUsers()
        {
            var access_token = SxApiParametersController.Repo.GetApiParameter("VK", "access_token");
            var groupId = SxApiParametersController.Repo.GetApiParameter("VK", "group_id");

            var request = new SX.VkApi.Request(access_token.Value);
            var response = request.Users.Search(new SX.VkApi.Parameters.Users.ParametersSearch()
            {
                Count = 12,
                GroupId= string.IsNullOrEmpty(groupId?.Value) ? (int?)null : Convert.ToInt32(groupId.Value),
                Fields = new SX.VkApi.Parameters.Users.ParametersSearch.UserSearchFields[] {
                    SX.VkApi.Parameters.Users.ParametersSearch.UserSearchFields.has_photo,
                    SX.VkApi.Parameters.Users.ParametersSearch.UserSearchFields.photo_50,
                    SX.VkApi.Parameters.Users.ParametersSearch.UserSearchFields.domain
                }
            });

            return response.Items;
        }
    }
}

simlex/Controllers/UsersController.cs
using SX.WebCore.MvcControllers;
using SX.WebCore.MvcControllers.Abstract;
using SX.WebCore.ViewModels;
using System;
using System.Collections.Generic;

namespace simlex.Controllers
{
    public sealed class UsersController : SxUsersController
    {
        protected override Action<SxBaseController, HashSet<SxVMBreadcrumb>> FillBreadcrumbs => Infrastructure.BreadcrumbsProvider.FillBreadcrumbs;
    }
}

simlex/Views/Shared/_AboutMe.cshtml
@{ 
    var logoImageId = SiteSettingsProvider["logo-image-id"]?.Value;
    var imageUrl = logoImageId != null ? Url.Action("Picture", "Pictures", new { id = logoImageId }) : "/content/dist/i/static/logo.png";
    var aboutSite=SiteSettingsProvider["sitedesc"]?.Value ?? "Описание сайта";
}
<div class="l-b about-me">
    <div class="about-me-img" style="background-image: url(@imageUrl);">
        <a href="@Url.Action("List", "Articles")"></a>
    </div>
    <h2 class="about-me-title">Привет, @("@username@")!</h2>
    <p class="about-me-text">
        @aboutSite
    </p>
</div>

simlex/Views/Shared/_AdsBlock.cshtml
<aside class="ads-block">
    <ul class="ads-block__list">
        <li>
            <div class="ads-block__item">
                <a href="#"> <img alt="demo" src="/content/dist/i/temp/ad-2.gif" /></a>
            </div>
        </li>
        <li>
            <div class="ads-block__item">
                <a href="#"> <img alt="demo" src="/content/dist/i/temp/ad-2.gif" /></a>
            </div>
        </li>
        <li>
            <div class="ads-block__item">
                <a href="#"> <img alt="demo" src="/content/dist/i/temp/ad-2.gif" /></a>
            </div>
        </li>
        <li>
            <div class="ads-block__item">
                <a href="#"> <img alt="demo" src="/content/dist/i/temp/ad-2.gif" /></a>
            </div>
        </li>
    </ul>
</aside>

simlex/Views/Shared/_Categories.cshtml
<div class="l-b categoties">
    <h4 class="categoties-title">Категории</h4>
    @Html.Action("TreeViewMenu", "MaterialCategories", new { mct=ModelCoreTypeProvider["Article"] })
</div>

simlex/Views/Shared/_Informer.cshtml
<aside class="site-informer">
    @*Yandex.Metrika informer*@
    <a href="https://metrika.yandex.ru/stat/?id=42333189&amp;from=informer" target="_blank" rel="nofollow"><img src="https://informer.yandex.ru/informer/42333189/3_1_FFFFFFFF_EFEFEFFF_0_pageviews" style="width:88px; height:31px; border:0;" alt="Яндекс.Метрика" title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)" class="ym-advanced-informer" data-cid="42333189" data-lang="ru" /></a>
</aside>

simlex/Views/Shared/_Layout.cshtml
@using SX.WebCore;
@{
    Layout = null;
    var lang = SiteSettingsProvider["lang"]?.Value ?? "ru";
    var title = ViewBag.Title == null ? SX.WebCore.MvcApplication.SxMvcApplication.DefaultSiteName : $"{ViewBag.Title} | {SX.WebCore.MvcApplication.SxMvcApplication.DefaultSiteName}";
    var isLocal = Request.IsLocal;
}
<!DOCTYPE html>
<html>
<head lang="@lang">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @if (!isLocal)
    {
        <meta name="google-site-verification" content="y_YyidDiRKd9oLQJKoIjEjLzPl64Lz-eKTniutaiq3Q" />
    }
    <meta property="og:url" content="@Url.ContentAbsUrl(Request.RawUrl)" />
    @if (title != null)
    {
        <title>@title</title>
        <meta property="og:title" content="@title" />
    }
    @if (ViewBag.Description != null)
    {
        <meta name="description" content="@ViewBag.Description" />
        <meta property="og:description" content="@ViewBag.Description" />
    }
    @if (ViewBag.Keywords != null)
    {
        <meta name="keywords" content="@ViewBag.Keywords" />
    }
    @if (ViewBag.PageImage != null)
    {
        var pageImgUrl = Url.ContentAbsUrl(Url.Action("Picture", "Pictures", new { id = ViewBag.PageImage }));
        <meta property="og:image" content="@pageImgUrl" />
    }
    @RenderSection("meta", false)
    <link href="@Url.Action("Css", "StaticContent", new { name = "bootstrap" })" rel="stylesheet" />
    <link href="@Url.Action("Css", "StaticContent", new { name = "font-awesome" })" rel="stylesheet" />
    <link href="~/content/dist/css/site.min.css" rel="stylesheet" />
    @RenderSection("styles", false)
</head>
<body>
    <div class="page-wrapper">
        @Html.Partial("_NavBar")
        <div class="page">
            <div class="page-col-2">
                @Html.Partial("_AboutMe")
                @Html.Partial("_Menu")
                @Html.Partial("_Categories")
                @Html.Partial("_Meta")
            </div>
            <div class="page-col-7">
                @if (Breadcrumbs != null && Breadcrumbs.Any())
                {
                    <div class="breadcrumbs">
                        @Html.SxBreadcrumbs(Breadcrumbs)
                    </div>
                }
                @RenderBody()
            </div>
            <div class="page-col-3">
                @Html.Partial("_AdsBlock")
                @Html.Action("Statistic", "Articles")
                @Html.Action("Accordion", "SiteNets")
                <div class="banner-right">
                    <img src="/content/dist/i/temp/addsens.jpg" style="max-width:100%;" />
                </div>
                @if (!isLocal)
                {
                    @Html.Partial("_Informer")
                }
            </div>
        </div>
    </div>
    <script src="@Url.Action("Js", "StaticContent", new { name="jquery"})"></script>
    <script src="@Url.Action("Js", "StaticContent", new { name="bootstrap"})"></script>
    <script src="@Url.Action("Js", "StaticContent", new { name="jquery.validate"})"></script>
    <script src="@Url.Action("Js", "StaticContent", new { name="jquery.validate.unobtrusive"})"></script>
    <script src="~/content/dist/js/site.min.js"></script>
    <script>
        $(function () {
            var page = new Page();
            page.initialize();

            var navbar = new Navbar();
            navbar.initialize('.nav-bar');
        });
    </script>
    @RenderSection("scripts", false)
    @if (!isLocal)
    {
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <script>
            (adsbygoogle = window.adsbygoogle || []).push({
                google_ad_client: "ca-pub-3457136546916064",
                enable_page_level_ads: true
            });
        </script>

        <script>
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date(); a = s.createElement(o),
                m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
            })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

            ga('create', 'UA-52276782-5', 'auto');
            ga('send', 'pageview');
        </script>

        <!-- Yandex.Metrika counter -->
        <script type="text/javascript">
            (function (d, w, c) {
                (w[c] = w[c] || []).push(function () {
                    try {
                        w.yaCounter42333189 = new Ya.Metrika({
                            id: 42333189,
                            clickmap: true,
                            trackLinks: true,
                            accurateTrackBounce: true
                        });
                    } catch (e) { }
                });

                var n = d.getElementsByTagName("script")[0],
                    s = d.createElement("script"),
                    f = function () { n.parentNode.insertBefore(s, n); };
                s.type = "text/javascript";
                s.async = true;
                s.src = "https://mc.yandex.ru/metrika/watch.js";

                if (w.opera == "[object Opera]") {
                    d.addEventListener("DOMContentLoaded", f, false);
                } else { f(); }
            })(document, window, "yandex_metrika_callbacks");
        </script>
        <noscript><div><img src="https://mc.yandex.ru/watch/42333189" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
        <!-- /Yandex.Metrika counter -->
    }
</body>
</html>

simlex/Views/Shared/_Menu.cshtml
@{
    var controller = ViewController;
}
<div class="l-b menu">
    <ul>
        <li @(controller == "articles" ? "class=active" : null)><a href="@Url.Action("List", "Articles")">Главная</a></li>
        <li @(controller == "users" ? "class=active" : null)><a href="@Url.Action("About", "Users", new { nikname="simlex"})">Контакты</a></li>
        <li class="get-site-btn"><a href="mailto:simlex.dev.2014@gmail.com">Заказать сайт</a></li>
        <li class="examples-site-btn @(controller == "projects" ? "active" : null)"><a href="@Url.Action("List", "Projects")">Проекты</a></li>
    </ul>
</div>

simlex/Views/Shared/_Meta.cshtml
@{
    var controller = ViewController;
}
<div class="l-b meta">
    <h4 class="meta-title">Ссылки</h4>
    <ul>
        @if (!User.Identity.IsAuthenticated)
        {
            <li @(controller == "account" ? "class=active" : null)><a href="@Url.Action("Login", "Account")">Вход</a></li>
        }
        else
        {
            <li>
                <form method="post" action="@Url.Action("Logoff", "Account")">
                    @Html.AntiForgeryToken()
                    <input type="hidden" name="url" value="@Url.Action("List", "Articles")" />
                    <a href="#" onclick="$(this).closest('form').submit(); return false;">Выход</a>
                </form>
            </li>
            <li><a href="@Url.Action("Index", "Home", new { area="admin"})">Управление</a></li>
        }
    </ul>
</div>

simlex/Views/Shared/_NavBar.cshtml
<nav>
    <div class="nav-bar">
        @Html.SxSiteNets(preWrite:()=>$"<li class=\"nav-bar--menu-btn\"><a href=\"#\"><i class=\"fa fa-reorder\"></i></a></li> <li class=\"nav-bar--toggle-btn\"><a href=\"#\"><i class=\"fa fa-link\"></i></a></li> <li class=\"nav-bar--search-btn\"><a href=\"#\"><i class=\"fa fa-search\"></i></a></li>", itemCssClass: "nav-bar-item")
    </div>
</nav>