simlex/Models/Article.cs
using SX.WebCore.DbModels;
using System.ComponentModel.DataAnnotations.Schema;

namespace simlex.Models
{
    [Table("D_ARTICLE")]
    public sealed class Article : SxArticle
    {
    }
}

simlex/Areas/Admin/Controllers/ArticlesController.cs
using simlex.Controllers.Abstract;
using simlex.Models;
using simlex.ViewModels;
using SX.WebCore.SxRepositories;
using simlex.Infrastructure.Repositories;
using SX.WebCore;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace simlex.Areas.Admin.Controllers
{
    public sealed class ArticlesController : MaterialsController<Article, VMArticle>
    {
        public ArticlesController() : base((byte)Enums.ModelCoreType.Article) { }

        private static RepoArticle _repo = new RepoArticle();
        public override SxRepoMaterial<Article, VMArticle> Repo
        {
            get
            {
                return _repo;
            }
        }

        public override async Task<ActionResult> Index(int page = 1)
        {
            ViewBag.Title = "Статьи";
            return await base.Index(page);
        }
    }
}

simlex/Areas/Admin/Controllers/StatisticsController.cs
using SX.WebCore.MvcControllers;

namespace simlex.Areas.Admin.Controllers
{
    public sealed class StatisticsController : SxStatisticsController
    {
    }
}

simlex/Controllers/ArticlesController.cs
using simlex.Models;
using simlex.ViewModels;
using SX.WebCore.SxRepositories;
using simlex.Infrastructure.Repositories;
using simlex.Controllers.Abstract;
using System.Web.Mvc;
using System.Threading.Tasks;
using SX.WebCore.MvcControllers;

namespace simlex.Controllers
{
    public sealed class ArticlesController : MaterialsController<Article, VMArticle>
    {
        public ArticlesController() : base(ModelCoreTypeProvider[nameof(Article)]) { }

        private static readonly RepoArticle _repo = new RepoArticle();
        public override SxRepoMaterial<Article, VMArticle> Repo
        {
            get
            {
                return _repo;
            }
        }

        [HttpGet]
        public async Task<ActionResult> Details(int year, string month, string day, string titleUrl)
        {
            var viewModel = await Repo.GetByTitleUrlAsync(year, month, day, titleUrl);
            if (viewModel == null) return new HttpNotFoundResult();
            viewModel.RelatedMaterials = await Repo.GetRelatedAsync<VMMaterial>(new SX.WebCore.SxFilter(1, 5) {
                MaterialId=viewModel.Id,
                ModelCoreType=viewModel.ModelCoreType
            });
            viewModel.Comments = await SxCommentsController.Repo.ReadAsync(new SX.WebCore.SxFilter(1, 10)
            {
                MaterialId=viewModel.Id,
                ModelCoreType=viewModel.ModelCoreType
            });

            return View(model: viewModel);
        }

#if !DEBUG
        [OutputCache(Duration = 3600)]
#endif
        public PartialViewResult Statistic()
        {
            var viewModel = new VMMaterialsStatisticBlock()
            {
                Materials = Repo.Read(new SX.WebCore.SxFilter(1, 10)),
                CommentedMaterials = Repo.LastCommented<VMMaterial>(new SX.WebCore.SxFilter(1, 10) { ModelCoreType=1 }),
                Tags = SxMaterialTagsController.Repo.GetCloud(new SX.WebCore.SxFilter(1, 10))
            };

            return PartialView("_Statistic", viewModel);
        }
    }
}

simlex/Controllers/CommentsController.cs
using SX.WebCore.MvcControllers;

namespace simlex.Controllers
{
    public sealed class CommentsController : SxCommentsController
    {
        
    }
}

simlex/Controllers/StaticContentController.cs
using SX.WebCore.MvcControllers;

namespace simlex.Controllers
{
    public sealed class StaticContentController : SxStaticContentController
    {
    }
}

simlex/Views/Articles/Details.cshtml
@model simlex.ViewModels.VMArticle
@{
    ViewBag.Title = Model.SeoTags?.SeoTitle ?? Model.Title;
    ViewBag.Description = Model.SeoTags?.SeoDescription ?? Model.Foreword;
    ViewBag.Keywords = Model.SeoTags?.KeywordsString ?? "simlex.online, статьи";
    ViewBag.PageImage = Model.SeoTags?.PageImageId ?? Model.FrontPictureId;
}
@section meta{
    <meta property="og:type" content="article" />
    <meta property="article:published_time" content="@Model.DateOfPublication.ToString("o")" />
    <meta property="article:modified_time" content="@Model.DateUpdate.ToString("o")" />
    <meta property="article:author" content="@Model.User.NikName" />
}

@Html.DisplayForModel()
@if (Model.RelatedMaterials.Any())
{
    @Html.Partial("_Related", Model)
}
<div id="comments-block">
    @Html.Partial("~/Views/Comments/_List.cshtml", Model.Comments, new ViewDataDictionary { { "MaterialId", Model.Id }, { "ModelCoreType", Model.ModelCoreType } })
</div>
@section scripts{
    <script src="@Url.Action("Js", "StaticContent", new { name="sxshare" })"></script>
    <script src="~/content/dist/js/sxcomments.min.js"></script>
    <script>
        $(function () {
            var comments = new SxComments('#comments-block', '@Url.Action("Edit", "Comments")', '#comments-block', function (form) {
                $(form).closest('.sx-new-comment').find('.fa-spinner').show();
            });
            comments.initialize();

            var share = new SxShare(".sxshare", true);
        });
    </script>

}

simlex/Views/Articles/List.cshtml
@using SX.WebCore.ViewModels;
@model SxExtantions.SxPagedCollection<simlex.ViewModels.VMArticle>
@{
    ViewBag.Title = ViewBag.Title ?? "Статьи";
    var tag = (SxVMMaterialTag)ViewBag.Tag;
    if (tag != null)
    {
        ViewBag.Title += $" с тегом {tag.Title}";
    }
    var category = (SxVMMaterialCategory)ViewBag.Category;
    if (category != null)
    {
        ViewBag.Title += $" категории {category.Title}";
    }
    var author = (SxVMAppUser)ViewBag.Author;
    if (author != null)
    {
        ViewBag.Title += $" автора {author.NikName}";
    }
    var page = ViewBag.Page;
    if (page > 1)
    {
        ViewBag.Title += $" [{page}]";
    }

}
<h1 class="hide">@(ViewBag.H1 ?? ViewBag.Title)</h1>
@if (Model.Collection.Any())
{
    for (int i = 0; i < Model.Collection.Length; i++)
    {
        @Html.DisplayFor(x => Model.Collection[i], new { Mode = "small" })
    }
}
else
{
    <div class="empty-page-panel">В данном разделе пока ничего не размещено, попробуйте зайти позднее...</div>
}

simlex/Views/Articles/_Related.cshtml
@model simlex.ViewModels.VMMaterial

<div class="rel-mats">
    <h4 class="rel-mats__header">Похожие статьи</h4>
    <ul>
        @for (int i = 0; i < Model.RelatedMaterials.Length; i++)
        {
            var item = Model.RelatedMaterials[i];
            <li>
                <h3 class="rel-mat__title">
                    <a href="@item.GetUrl(Url)" title="@item.Title">@item.Title</a>
                </h3>
                <div class="rel-mat__date">
                    @item.DateOfPublication.ToString("dd MMM, yyyy")
                </div>
            </li>
        }
    </ul>
</div>

simlex/Views/Articles/_Statistic.cshtml
@model simlex.ViewModels.VMMaterialsStatisticBlock

<aside class="mat-stat">

    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#posts" aria-controls="posts" role="tab" data-toggle="tab">Статьи</a></li>
        <li role="presentation"><a href="#comments" aria-controls="comments" role="tab" data-toggle="tab">Комментарии</a></li>
        <li role="presentation"><a href="#tags" aria-controls="tags" role="tab" data-toggle="tab">Теги</a></li>
    </ul>

    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="posts">
            <ul class="mat-stat__materials">
                @for (int i = 0; i < Model.Materials.Length; i++)
                {
                    var material = Model.Materials[i];
                    <li>
                        <i class="fa fa-file-text-o"></i> <a href="@material.GetUrl(Url)">@material.Title</a>
                    </li>
                }
            </ul>
        </div>
        <div role="tabpanel" class="tab-pane" id="comments">
            <ul class="mat-stat__comments">
                @for (int i = 0; i < Model.CommentedMaterials.Length; i++)
                {
                    var commentedMaterial = Model.CommentedMaterials[i];

                    <li>
                        <i class="fa fa-comment-o"></i> <span class="mat-stat__comment-author">@(commentedMaterial.LastComment.User?.NikName ?? commentedMaterial.LastComment?.UserName)</span> <a href="@($"{commentedMaterial.GetUrl(Url)}#sx-comment-{commentedMaterial.LastComment.Id}")">@commentedMaterial.Title</a>
                    </li>
                }
            </ul>
        </div>
        <div role="tabpanel" class="tab-pane" id="tags">
            @Html.SxTagsCloud(Model.Tags, x => Url.Action("List", "Articles", new { tag = x.Id }), 14, false)
        </div>
    </div>

</aside>