simlex/Areas/Admin/Controllers/UserContactsController.cs
using SX.WebCore.MvcControllers;

namespace simlex.Areas.Admin.Controllers
{
    public sealed class UserContactsController : SxUserContactsController
    {
    }
}

simlex/Controllers/StaticContentController.cs
using SX.WebCore.MvcControllers;

namespace simlex.Controllers
{
    public sealed class StaticContentController : SxStaticContentController
    {
    }
}

simlex/Areas/Admin/Views/UserContacts/Edit.cshtml
@model SxVMUserContact

@{
    var isNew = !Model.ContactType.HasValue;
    var user = (SxVMAppUser)ViewBag.User;
    ViewBag.Title = $"{(isNew ? "Добавление" : "Редактирование")} контакта пользователя {user.NikName}";
}

<h2>@ViewBag.Title</h2>
<br />

<form method="post" action="@Url.Action("Edit")">
    @Html.AntiForgeryToken()
    @Html.HiddenFor(x => x.UserId)
    @Html.HiddenFor(x => x.OldContactType)

    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                @Html.LabelFor(x => x.ContactType, new { @class = "control-label" })
                @if (Model.OldContactType.HasValue)
                {
                    @Html.EnumDropDownListFor(x => x.ContactType, new { @class = "form-control", @disabled = "disabled" })
                    @Html.HiddenFor(x => x.ContactType)
                }
                else
                {
                    @Html.EnumDropDownListFor(x => x.ContactType, new { @class = "form-control" })
                }

                @Html.ValidationMessageFor(x => x.ContactType)
            </div> 
        </div>
        <div class="col-md-9">
            <div class="form-group">
                @Html.LabelFor(x => x.Value, new { @class = "control-label" })
                @Html.EditorFor(x => x.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(x => x.Value)
            </div>
        </div>
    </div>

    <div class="form-group">
        <a href="@Url.Action("Index", "UserContacts", new { userId=user.Id})" class="btn btn-default">Назад</a>
        <button type="submit" class="btn btn-primary">@(isNew ? "Добавить" : "Править")</button>
    </div>
</form>

@section scripts{
    <script src="@Url.Action("Js", "StaticContent", new { name="jquery.validate", area=""})"></script>
    <script src="@Url.Action("Js", "StaticContent", new { name="jquery.validate.unobtrusive", area=""})"></script>
}

simlex/Areas/Admin/Views/UserContacts/Index.cshtml
@model SxVMUserContact[]

@{ 
    var user = (SxVMAppUser)ViewBag.User;
    ViewBag.Title = $"Контакты пользователя {user.NikName}";
}

<h2>@ViewBag.Title</h2>
<br />

<div id="user-contacts">
    @Html.Partial("_GridView", Model)
</div>

@section scripts{
    <script>
        $(function () {
            var grid = new SxGridView('#user-contacts');
        });
    </script>
}

simlex/Areas/Admin/Views/UserContacts/_GridView.cshtml
@model SxVMUserContact[]
@{
    var user = (SxVMAppUser)ViewBag.User;
}

@Html.SxGridView(Model, new SxExtantions.SxGridViewSettings<SxVMUserContact>()
{
    Columns = new SxExtantions.SxGridViewColumn<SxVMUserContact>[] {
        new SxExtantions.SxGridViewColumn<SxVMUserContact>() { Caption="Тип", FieldName="ContactType" },
        new SxExtantions.SxGridViewColumn<SxVMUserContact>() { Caption = "Значение", FieldName="Value" }
    },
    DataAjaxUrl = Url.Action("Index", "UserContacts", new { userId = user.Id }),
    EnableCreating = true,
    CreateRowUrl = Url.Action("Edit", "UserContacts", new { userId = user.Id }),
    EnableEditing=true,
    EditRowUrl=x=> Url.Action("Edit", "UserContacts", new { userId = user.Id, ct=x.ContactType })
})